### ISSUE TITLE
maven镜像仓库问题

### ISSUE THREAD

**Issue by Allenzero1** [LovebuildJ/book-manager#1]
博主你用的maven的镜像仓库是哪个，我用的阿里云的镜像。但是好像没有  spring-boot-starter-parent 这个 2.3.1-RELEASE.能分享下你的setting.xml文件吗

**Comment by LovebuildJ** [comment]
好的，镜像内容如下，已提交至wiki。
https://github.com/LovebuildJ/book-manager/wiki
